language: python

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

jobs:
  include:
  - stage: test
    python: '3.5'	
    script:
    - python -m pytest -v --cov=./moiety_modeling

  - stage: test
    python: '3.6'
    script:
    - python -m pytest -v --cov=./moiety_modeling

  - stage: test
    python: '3.7'
    dist: xenial
    script:
    - python -m pytest -v --cov=./moiety_modeling

after_success:
  - codecov
