language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
   
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

script:
  - python -m pytest -v --cov=./moiety_modeling

after_success:
  - codecov
